blog/config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'

  get 'sessions/new'

  get "sessions/create"

  get "sessions/destroy"

  resources :users
  resources :posts
    

get 'admin' => 'admin#index'
get 'orgpages/index' => 'orgpages#org'

controller :sessions do 
get 'login' => :new
post 'login' => :create
delete 'logout' => :destroy

end
resources :orgpages

  root 'admin#index'

 
end

blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

blog/app/models/orgpage.rb
class Orgpage < ActiveRecord::Base
end

blog/app/models/post.rb
class Post < ActiveRecord::Base
end

blog/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

blog/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
 # protect_from_forgery with: :exception
#before_action :authorize 
#protected
#def authorize
#unless User.find_by(id: session[:user_id])
#redirect_to admin_url , notice:"Unauthorized access"
#end
#end
end

blog/app/controllers/orgpages_controller.rb
class OrgpagesController < ApplicationController
	
  before_action :set_orgpage, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @orgpages= Orgpage.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @orgpage = Orgpage.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @orgpage = Orgpage.new(orgpage_params)

    respond_to do |format|
      if @orgpage.save
        format.html { redirect_to @orgpage, notice: 'Org Page was successfully created.' }
        format.json { render :show, status: :created, location: @orgpage }
      else
        format.html { render :new }
        format.json { render json: @orgpage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @orgpage.update(orgpage_params)
        format.html { redirect_to @orgpage, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @orgpage }
      else
        format.html { render :edit }
        format.json { render json: @orgpage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @orgpage.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orgpage
      @orgpage = Orgpage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def orgpage_params
      params.require(:orgpage).permit(:title, :body)
    end
end

blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

blog/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_before_action :authorize
  def new
  end

  def create
  	user = User.find_by(name: params[:name])
  	if user and user.authenticate(params[:password])
  		sessions[:user_id] = user.id
  		redirect_to admin_url
  	else
  		redirect_to login_url , alert:"Invalid username or password"
  	end
  end

  def destroy
  	sessions[:user_id] = nil
  	redirect_to login_url , alert:"Successfully logged out"
  end
end

blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
#skip_before_action :authorize , only: [:new, :create, :index]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

blog/app/helpers/admin_helper.rb
module AdminHelper
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/posts_helper.rb
module PostsHelper
end

blog/app/helpers/sessions_helper.rb
module SessionsHelper
end

blog/app/helpers/users_helper.rb
module UsersHelper
end

blog/app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>ClubHub</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= stylesheet_link_tag  "style" %>
    <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <style>
    @font-face {
    font-family: 'FontAwesome';
    src: url(font-path('fontawesome-webfont.eot') + '?v=4.4.0');
    src: url(font-path('fontawesome-webfont.eot') + '?#iefix&v=4.4.0') format('embedded-opentype'),
         url(font-path('fontawesome-webfont.woff2') + '?v=4.4.0') format('woff2'),
         url(font-path('fontawesome-webfont.woff') + '?v=4.4.0') format('woff'),
         url(font-path('fontawesome-webfont.ttf') + '?v=4.4.0') format('truetype'),
         url(font-path('fontawesome-webfont.svg') + '?v=4.4.0#fontawesomeregular') format('svg');
    font-weight: normal;
    font-style: normal;
}
    </style>
</head>
<body>
</head>
<body>
    
    <body class="landing">
		<div id="page-wrapper">

			<!-- Header -->
				<header id="header" class="alt">
					<h1><%= link_to 'ClubHub', posts_path %></h1>
					<nav id="nav">
						<ul>
                            <li><%= link_to 'Home', posts_path %></li>
							<li>
								<a href="#" class="icon fa-angle-down">User Options</a>
								<ul>
                                        <!--Drop-down menu not working-->
									<li>
										<a href="#">Submenu</a>
										<ul>
											<li><a href="#">About Me</a></li>
											<li><a href="#">Write A Review</a></li>
											<li><a href="#">Find Friends</a></li>
											<li><a href="#">Talk</a></li>
                                            <li><a href="generic.html">Write A Review</a></li>
									       <li><a href="contact.html">Make A New Site</a></li>
									       <li><a href="elements.html">Elements</a></li>
										</ul>
									</li>
								</ul>
							</li>
							<li><a href="#" class="button">Sign Up</a></li>
						</ul>
                         <form class="form-inline">
                  <div class="form-group">
                    <h6>Username</h6>
                    <input type="text" class="form-control" placeholder="Username">
                  </div>
                  <div class="form-group">
                    <h6>Password</h6>
                    <input type="email" class="form-control" placeholder="**********">
                      <button type="submit" class="btn btn-default">Submit</button>
                  </div>
                </form>
					</nav>
				</header>
    
    	<section id="banner">
					<h1 style="font-size:150px">ClubHub</h1>
					<p>Designed by &copy;Codiggers</p>

				</section>

			<!-- Main -->
				<section id="main" class="container">

					<section class="box special">
						<header class="major">
							<h2>Introducing the ultimate SJSU club organization finder.</h2>
							<p>SJSU ClubHub was designed in order to provide students at SJSU the opportunity to learn about the different student organizations on campus. </p>
						</header>
						<span class="image featured"><img src="http://campaign.sjsu.edu/cmsimages/SJSU-ACCEL-DM_Page_06.jpg" alt="" /></span>
					</section>

					<section class="box special features">
                        <h1>Reviews of the day!</h1>
						<div class="features-row">
							<section>
								<span class="icon major fa-bolt accent2"></span>
								<h3>Club one</h3>
								<p>Integer volutpat ante et accumsan commophasellus sed aliquam feugiat lorem aliquet ut enim rutrum phasellus iaculis accumsan dolore magna aliquam veroeros.</p>
							</section>
							<section>
								<span class="icon major fa-area-chart accent3"></span>
								<h3>Club two</h3>
								<p>Integer volutpat ante et accumsan commophasellus sed aliquam feugiat lorem aliquet ut enim rutrum phasellus iaculis accumsan dolore magna aliquam veroeros.</p>
							</section>
						</div>
						<div class="features-row">
							<section>
								<span class="icon major fa-cloud accent4"></span>
								<h3>Club three</h3>
								<p>Integer volutpat ante et accumsan commophasellus sed aliquam feugiat lorem aliquet ut enim rutrum phasellus iaculis accumsan dolore magna aliquam veroeros.</p>
							</section>
							<section>
								<span class="icon major fa-lock accent5"></span>
								<h3>Club four</h3>
								<p>Integer volutpat ante et accumsan commophasellus sed aliquam feugiat lorem aliquet ut enim rutrum phasellus iaculis accumsan dolore magna aliquam veroeros.</p>
							</section>
						</div>
					</section>
<center><h2>Featured clubs for the month of May</h2></center>
					<div class="row">
                        <div class="6u 12u(narrower)">

							<section class="box special">
								<img src="http://www.swe.uc.edu/_pictures/_logos/swe_logo.jpg" width="300px" height="auto"/>
								<h3>Society of Women Engineers</h3>
								<p>Integer volutpat ante et accumsan commophasellus sed aliquam feugiat lorem aliquet ut enim rutrum phasellus iaculis accumsan dolore magna aliquam veroeros.</p>
								<ul class="actions">
									<li><a href="#" class="button alt">Learn More</a></li>
								</ul>
							</section>

						</div>
						<div class="6u 12u(narrower)">

							<section class="box special">
								<img src="http://www.fuelyourcreativity.com/files/2009/02/logo3.png" width="375px" height="auto"/>
								<h3>Codiggers</h3>
								<p>Integer volutpat ante et accumsan commophasellus sed aliquam feugiat lorem aliquet ut enim rutrum phasellus iaculis accumsan dolore magna aliquam veroeros.</p>
								<ul class="actions">
									<li><a href="#" class="button alt">Learn More</a></li>
								</ul>
							</section>

						</div>
					</div>

				</section>

			<!-- CTA -->
				<section id="cta">

                    <h2>Subscribe</h2>

					<form>
						<div class="row uniform 50%">
							<div class="8u 12u(mobilep)">
								<input type="email" name="email" id="email" placeholder="Email Address" />
							</div>
							<div class="4u 12u(mobilep)">
								<input type="submit" value="Sign Up" class="fit" />
							</div>
						</div>
					</form>

				</section>


		</div>


        <%= yield %>

        			<!-- Footer -->
				<footer id="footer">
					<ul>
						<li><a href = "www.twitter.com" class="btn btn-social-icon btn-twitter"><span class="fa fa-twitter"></span></a></a></li>
                        <li><a href = "www.facebook.com" class="btn btn-social-icon btn-facebook"><span class="fa fa-facebook"></span></a></li>
                        <li><a href = "www.instagram.com" class="btn btn-social-icon btn-instagram"><span class="fa fa-instagram"></span></a></li>
                        <li><a href = "www.github.com" class="btn btn-social-icon btn-github"><span class="fa fa-github"></span></a></li>
                        <li><a href = "www.google.com" class="btn btn-social-icon btn-google"><span class="fa fa-google"></span></a></li>
                        </ul>
					<ul class="copyright">
						<li>&copy;Codiggers. All rights reserved.</li>
					</ul>
				</footer>
            <script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/jquery.dropotron.min.js"></script>
			<script src="assets/js/jquery.scrollgress.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/util.js"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="assets/js/main.js"></script>


</body>
</html>

blog/app/views/orgpages/_form.html.erb
<%= form_for(@orgpage) do |f| %>
  <% if @orgpage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@orgpage.errors.count, "error") %> prohibited this orgpage from being saved:</h2>

      <ul>
      <% @orgpage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blog/app/views/orgpages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form' %>

<%= link_to 'Show', @orgpage %> |

blog/app/views/orgpages/index.html.erb
<h1>Orgpages#index</h1>
<p>Find me in app/views/orgpages/index.html.erb</p>

<center>
<h1>Newsfeed</h1>
<div class="row medium-8 large-7 columns">
<div class="organization-page">

<% @orgpage.each do |orgpage| %>
 <h2><%= link_to orgpage.title, orgpage %></h2>
    <img class="thumbnail" src="http://placehold.it/850x350">

 <p><%= orgpage.body %></p>
 <p>

 <%= link_to 'Edit', edit_orgpage_path(orgpage) %>|<%= link_to 'Destroy', orgpage, method: :delete,
 data: { confirm: 'Are you sure?' } %>
 </p>
<% end %>
    

</div>
</div>
    
</div>

<br>

<%= link_to 'New Organization Page', new_orgpage_path %>

</center>

blog/app/views/orgpages/new.html.erb
<h1>New Org Page</h1>

<%= render 'form' %>

<%= link_to 'Back', orgpages_path %>

blog/app/views/orgpages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @orgpage.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @orgpage.body %>
</p>

<%= link_to 'Edit', edit_orgpage_path(@orgpages) %> |
<%= link_to 'Back', orgpages_path %>

blog/app/views/posts/_form.html.erb
<style>       
.margins{
            margin-left:120px;
            float:left;
        }
    .text{
        font-size:20px;
    }
</style>

<div class="margins">

<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <%= f.label :title, :class => "text" %><br> 
      <%= f.text_field :title, :class =>"form-control" %>
    
  </div>
  <div class="field">
    <%= f.label :body, :class => "text" %><br>
    <%= f.text_area :body, :class =>"form-control" %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-default" %>
  </div>
<% end %>

</div>

blog/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

blog/app/views/posts/index.html.erb
<div class="row medium-8 large-7 columns">
<div class="blog-post">

<% @posts.each do |post| %>
 <h2><%= link_to post.title, post %></h2>
    <img class="thumbnail" src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcT3xlrfdjuY8YXjAjTpaRYA8YXUnD1CvxyTifdwIkw7pvjh8MuW">

 <p><%= post.body %></p>
 <p>

 <%= link_to 'Edit', edit_post_path(post) %>|<%= link_to 'Destroy', post, method: :delete,
 data: { confirm: 'Are you sure?' } %>
 </p>
<% end %>
    

</div>
</div>
    
</div>

<br>

<p style="margin-left:120px"><%= link_to 'New Post', new_post_path %></p>

</div>

blog/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

blog/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

blog/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blog/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

blog/app/views/users/index.html.erb
<h1>Listing users</h1>
<% if notice %>
<p id="notice" > <%= notice %>
  </p>
  
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<% end %>

blog/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

blog/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>